#!/usr/bin/env sh
echo "Running pre-commit checks..."

echo "Formatting Go code..."
cd golang && go fmt ./... && cd ..
if [ $? -ne 0 ]; then
  echo "Go formatting failed. Please fix the issues before committing."
  exit 1
fi

echo "Linting nextjs..."
cd nextjs && npm run lint && cd ..
if [ $? -ne 0 ]; then
  echo "Next.js linting failed. Please fix the issues before committing."
  exit 1
fi

echo "Pre-commit checks passed!"
