#!/usr/bin/env sh
echo "Running pre-push checks..."

echo "Building Go..."
cd golang && go build -o /dev/null . && cd ..
if [ $? -ne 0 ]; then
  echo "Go build failed. Please fix the issues before pushing."
  exit 1
fi

echo "Building nextjs..."
cd nextjs && npm run build && cd ..
if [ $? -ne 0 ]; then
  echo "Web build failed. Please fix the issues before pushing."
  exit 1
fi

echo "Linting reactnative..."
cd reactnative && npm run lint && cd ..
if [ $? -ne 0 ]; then
  echo "React Native linting failed. Please fix the issues before pushing."
  exit 1
fi

echo "All pre-push checks passed!"

